name1 = input("Enter a name: ")
noun1 = input("Enter a noun: ")
noun2 = input("Enter a plural noun: ")
noun3 = input("Enter a third noun: ")
noun4 = input("Enter a forth noun: ")
noun5 = input("Enter a fifth noun: ")
adjective1 = input("Enter an adjective: ")
adjective2 = input("Enter another adjective: ")
verb1 = input("Enter a verb: ")
pastverb1 = input("Enter a past-tense verb: ")
verbed1 = input("Enter a verb ending in 'ed': ")
adverb1 = input("Enter an adverb: ")
location1 = input("Enter a place or thing: ")
number1 = input("Enter a number: ")

print("\n")
print("The Store")
print("\n")
print("Today, " + name1 + " had " + pastverb1)
print("to the " + location1 + " store. " + name1 + " needed to get")
print(noun1 + ", some " + noun2 + ", and a " + noun3 + ".")
print("\n")
print(number1 + " minutes later, " + name1 + " arrived at the " + location1 + " store.")
print(name1 + " found the " + noun1 + " and " + noun3 + " " + adverb1 + ",")
print("picking up " + noun4 + " and a " + noun5 + " along the way.")
print("When " + name1 + " found the " + noun2 + ", it was " + adjective1 + ",")
print("so " + name1 + " " + verbed1 + " it away.")
print("\n")
print(name1 + " finished shopping, leaving without the " + noun2 + ".")
print("Shopping took a while, as the sky was " + adjective2 + " already.")
print(name1 + " " + verb1 + "ed home.")
print("\n")
print("The End")