name1 = input("Enter a name: ")
adjective1 = input("Enter an adjective: ")
adjective2 = input("Enter another adjective: ")
adverb1 = input("Enter an adverb: ")
food1 = input("Enter a food: ")
food2 = input("Enter another food: ")
noun1 = input("Enter a noun: ")
place1 = input("Enter a place: ")
verb1 = input("Enter a verb: ")

print(name1 + " was planning a dream vacation to " + place1 + ".")
print(name1 + " was especially looking forward to trying the local")
print("cuisine, including " + adjective1 + " " + food1 + " and " + food2 + ".")
print("\n")
print(name1 + " will have to practice the language " + adverb1 + " to")
print("make it easier to " + verb1 + " with people.")
print("\n")
print(name1 + " has a long list of sights to see, including the")
print(noun1 + " museum and the " + adjective2 + " park.")
